{{ config( 
        materialized='incremental',
        unique_key='unique_key'
) }}

{%- set schema_name, table_name = 'pinterest_raw', 'ad_group_report' -%}
{% set raw_tables = dbt_utils.get_relations_by_pattern('pinterest_raw%', 'ad_group_report') %}

{%- set exclude_fields = [
    "campaign_status",
    "campaign_daily_spend_cap",
    "campaign_lifetime_spend_cap",
    "cpc_in_micro_dollar",
    "cpcv_in_micro_dollar",
    "cpcv_p_95_in_micro_dollar",
    "cpm_in_micro_dollar",
    "cpv_in_micro_dollar",
    "ctr_2",
    "ctr",
    "ecpc_in_micro_dollar",
    "ecpm_in_micro_dollar",
    "ectr",
    "engagement_1",
    "engagement_2",
    "video_p_0_combined_1",
    "video_p_0_combined_2",
    "video_p_25_combined_1",
    "video_p_25_combined_2",
    "video_p_50_combined_1",
    "video_p_50_combined_2",
    "video_p_75_combined_1",
    "video_p_75_combined_2",
    "video_p_95_combined_1",
    "video_p_95_combined_2",
    "total_video_3_sec_views", 
    "video_3_sec_views_1",
    "video_3_sec_views_2",
    "video_mrc_views_1",
    "video_mrc_views_2",
    "video_avg_watchtime_in_second_1",
    "video_avg_watchtime_in_second_2",
    "total_add_to_cart_desktop_action_to_desktop_conversion",
    "total_add_to_cart_desktop_action_to_mobile_conversion",
    "total_add_to_cart_desktop_action_to_tablet_conversion",
    "total_add_to_cart_mobile_action_to_desktop_conversion",
    "total_add_to_cart_mobile_action_to_tablet_conversion",
    "total_add_to_cart_mobile_action_to_mobile_conversion",
    "total_add_to_cart_tablet_action_to_mobile_conversion",
    "total_add_to_cart_tablet_action_to_desktop_conversion",
    "total_add_to_cart_tablet_action_to_tablet_conversion",
    "total_web_add_to_cart",
    "total_web_add_to_cart_value_in_micro_dollar",
    "total_web_view_add_to_cart_value_in_micro_dollar",
    "total_web_view_add_to_cart",
    "total_web_click_add_to_cart_value_in_micro_dollar",
    "total_web_click_add_to_cart",
    "total_custom_desktop_action_to_desktop_conversion",
    "total_custom_mobile_action_to_desktop_conversion",
    "total_custom_mobile_action_to_mobile_conversion",
    "total_custom_tablet_action_to_desktop_conversion",
    "total_custom_tablet_action_to_mobile_conversion",
    "total_custom_tablet_action_to_tablet_conversion",
    "total_web_custom",
    "total_web_custom_value_in_micro_dollar",
    "total_web_view_custom",
    "total_web_view_custom_value_in_micro_dollar",
    "total_web_click_custom",
    "total_web_click_custom_value_in_micro_dollar",
    "total_checkout_desktop_action_to_desktop_conversion",
    "total_checkout_desktop_action_to_mobile_conversion",
    "total_checkout_desktop_action_to_tablet_conversion",
    "total_checkout_mobile_action_to_desktop_conversion",
    "total_checkout_mobile_action_to_mobile_conversion",
    "total_checkout_mobile_action_to_tablet_conversion",
    "total_checkout_tablet_action_to_desktop_conversion",
    "total_checkout_tablet_action_to_mobile_conversion",
    "total_checkout_tablet_action_to_tablet_conversion",
    "total_web_view_checkout",
    "total_web_view_checkout_value_in_micro_dollar",
    "total_web_click_checkout",
    "total_web_click_checkout_value_in_micro_dollar",
    "total_web_checkout_value_in_micro_dollar",
    "total_web_checkout",
    "total_page_visit_desktop_action_to_desktop_conversion",
    "total_page_visit_desktop_action_to_mobile_conversion",
    "total_page_visit_desktop_action_to_tablet_conversion",
    "total_page_visit_mobile_action_to_desktop_conversion",
    "total_page_visit_mobile_action_to_mobile_conversion",
    "total_page_visit_mobile_action_to_tablet_conversion",
    "total_page_visit_tablet_action_to_desktop_conversion",
    "total_page_visit_tablet_action_to_mobile_conversion",
    "total_page_visit_tablet_action_to_tablet_conversion",
    "total_view_page_visit_quantity",
    "total_view_page_visit_value_in_micro_dollar",
    "total_view_page_visit",
    "total_web_page_visit",
    "total_web_page_visit_value_in_micro_dollar",
    "total_web_view_page_visit_value_in_micro_dollar",
    "total_web_view_page_visit",
    "total_web_click_page_visit",
    "total_click_page_visit_quantity",
    "total_click_page_visit_value_in_micro_dollar",
    "total_click_page_visit",
    "total_web_click_page_visit_value_in_micro_dollar",
    "total_search_desktop_action_to_desktop_conversion",
    "total_search_desktop_action_to_mobile_conversion",
    "total_search_mobile_action_to_desktop_conversion",
    "total_search_mobile_action_to_mobile_conversion",
    "total_search_mobile_action_to_tablet_conversion",
    "total_search_tablet_action_to_desktop_conversion",
    "total_search_tablet_action_to_mobile_conversion",
    "total_search_tablet_action_to_tablet_conversion", 
    "total_view_search",
    "total_web_search",
    "total_web_view_search",
    "total_click_search",
    "total_web_click_search",
    "total_view_category_desktop_action_to_desktop_conversion",
    "total_view_category_desktop_action_to_tablet_conversion",
    "total_view_category_desktop_action_to_mobile_conversion",
    "total_view_category_mobile_action_to_desktop_conversion",
    "total_view_category_mobile_action_to_mobile_conversion",
    "total_view_category_mobile_action_to_tablet_conversion",
    "total_view_category_tablet_action_to_desktop_conversion",
    "total_view_category_tablet_action_to_mobile_conversion",
    "total_view_category_tablet_action_to_tablet_conversion",
    "total_view_view_category",
    "total_web_view_category",
    "total_web_view_view_category",
    "total_web_click_view_category",
    "total_click_view_category",
    "total_web_engagement_signup",
    "total_web_engagement_search",
    "total_web_engagement_lead",
    "total_web_engagement_view_category",
    "total_web_engagement_page_visit",
    "total_web_engagement_page_visit_value_in_micro_dollar",
    "total_web_engagement_add_to_cart",
    "total_web_engagement_add_to_cart_value_in_micro_dollar",
    "total_web_engagement_checkout",
    "total_web_engagement_checkout_value_in_micro_dollar",
    "total_engagement_lead",
    "total_engagement_add_to_cart_quantity",
    "total_engagement_add_to_cart_value_in_micro_dollar",
    "total_engagement_add_to_cart",
    "total_engagement_checkout_quantity",
    "total_engagement_checkout",
    "total_engagement_checkout_value_in_micro_dollar",
    "total_engagement_page_visit",
    "total_engagement_page_visit_quantity",
    "total_engagement_page_visit_value_in_micro_dollar",
    "total_engagement_search",
    "total_engagement_signup",
    "total_engagement_view_category",
    "total_engagement",
    "total_lead_desktop_action_to_desktop_conversion",
    "total_lead_desktop_action_to_mobile_conversion",
    "total_lead_mobile_action_to_desktop_conversion",
    "total_lead_mobile_action_to_mobile_conversion",
    "total_lead_mobile_action_to_tablet_conversion",
    "total_lead_tablet_action_to_desktop_conversion",
    "total_lead_tablet_action_to_mobile_conversion",
    "total_lead_tablet_action_to_tablet_conversion",
    "total_web_lead",
    "total_web_view_lead",
    "total_web_click_lead",
    "total_signup_desktop_action_to_desktop_conversion",
    "total_signup_desktop_action_to_mobile_conversion",
    "total_signup_mobile_action_to_desktop_conversion",
    "total_signup_mobile_action_to_mobile_conversion",
    "total_signup_mobile_action_to_tablet_conversion",
    "total_signup_tablet_action_to_desktop_conversion",
    "total_signup_tablet_action_to_mobile_conversion",
    "total_signup_tablet_action_to_tablet_conversion",
    "total_web_signup",
    "total_web_signup_value_in_micro_dollar",
    "total_web_view_signup",
    "total_web_view_signup_value_in_micro_dollar",
    "total_web_click_signup",
    "total_unknown_desktop_action_to_desktop_conversion",
    "total_unknown_mobile_action_to_desktop_conversion",
    "total_unknown_mobile_action_to_mobile_conversion",
    "total_unknown_tablet_action_to_desktop_conversion",
    "total_unknown_tablet_action_to_mobile_conversion",
    "total_view_unknown",
    "total_click_unknown",
    "total_web_unknown",
    "total_web_view_unknown",
    "total_web_click_unknown"
]
-%}

{%- set fields = adapter.get_columns_in_relation(source(schema_name, table_name))
                    |map(attribute="name")
                    |reject("in",exclude_fields)
                    -%}  

WITH raw_data AS 
    ({{ dbt_utils.union_relations(relations = raw_tables) }}),

    staging AS 
    (SELECT 
        {%- for field in fields if ("cost_per" not in field and "_roas" not in field) %}
        {{ get_pinterest_clean_field(table_name, field) }}
        {%- if not loop.last %},{%- endif %}
        {%- endfor %}
    FROM raw_data
    )

SELECT 
    *,
    MAX(_fivetran_synced) over () as last_updated,
    ad_group_id||'_'||date as unique_key
FROM staging
{% if is_incremental() -%}

  -- this filter will only be applied on an incremental run
where date >= (select max(date)-30 from {{ this }})

{% endif %}
